
-- DBMS LAB 5
-- INNER JOIN Queries
-- ==========================================

-- ========== PART A ==========

-- 1
SELECT S.STUDENT_ID, S.NAME, E.COURSE_ID
FROM STUDENT S
INNER JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID;

-- 2
SELECT S.NAME, E.SEMESTER
FROM STUDENT S
INNER JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID;

-- 3
SELECT S.NAME, E.GRADE
FROM STUDENT S
INNER JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID;


-- ========== PART B ==========

-- 4
SELECT C.COURSE_NAME, C.CREDITS, F.NAME AS FACULTY_NAME
FROM COURSE C
INNER JOIN FACULTY F
ON C.FACULTY_ID = F.FACULTY_ID;

-- 5
SELECT C.COURSE_NAME
FROM COURSE C
INNER JOIN FACULTY F
ON C.FACULTY_ID = F.FACULTY_ID
WHERE F.FACULTY_ID = 201;

-- 6
SELECT F.NAME, F.DESIGNATION, C.COURSE_NAME
FROM FACULTY F
INNER JOIN COURSE C
ON F.FACULTY_ID = C.FACULTY_ID;


-- ========== PART C ==========

-- 7
SELECT S.NAME, C.COURSE_NAME
FROM STUDENT S
INNER JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID
INNER JOIN COURSE C
ON E.COURSE_ID = C.COURSE_ID;

-- 8
SELECT S.NAME, C.COURSE_NAME, E.SEMESTER
FROM STUDENT S
INNER JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID
INNER JOIN COURSE C
ON E.COURSE_ID = C.COURSE_ID;

-- 9
SELECT S.NAME, C.COURSE_NAME, E.GRADE
FROM STUDENT S
INNER JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID
INNER JOIN COURSE C
ON E.COURSE_ID = C.COURSE_ID
WHERE E.SEMESTER = '2nd Sem';

-- 10
SELECT C.COURSE_NAME
FROM STUDENT S
INNER JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID
INNER JOIN COURSE C
ON E.COURSE_ID = C.COURSE_ID
WHERE S.STUDENT_ID = 1;


-- ========== PART D ==========

-- 11
SELECT S.NAME, S.DEPARTMENT_ID, C.COURSE_NAME
FROM STUDENT S
INNER JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID
INNER JOIN COURSE C
ON E.COURSE_ID = C.COURSE_ID;


-- 12
SELECT D.DEPARTMENT_ID, C.COURSE_NAME
FROM DEPARTMENT D
INNER JOIN COURSE C
ON D.DEPARTMENT_ID = C.DEPARTMENT_ID;

-- 13
SELECT F.NAME, D.DEPARTMENT_NAME
FROM FACULTY F
INNER JOIN DEPARTMENT D
ON F.DEPARTMENT_ID = D.DEPARTMENT_ID;


-- ========== PART E ==========

-- 14
SELECT S.NAME, C.COURSE_NAME
FROM STUDENT S
INNER JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID
INNER JOIN COURSE C
ON E.COURSE_ID = C.COURSE_ID
WHERE S.DEPARTMENT_ID = 2;

-- 15
SELECT S.NAME, C.COURSE_NAME
FROM STUDENT S
INNER JOIN ENROLLMENT E
ON S.STUDENT_ID = E.STUDENT_ID
INNER JOIN COURSE C
ON E.COURSE_ID = C.COURSE_ID
ORDER BY S.NAME ASC;

-- 16
SELECT F.NAME, C.COURSE_NAME
FROM FACULTY F
INNER JOIN COURSE C
ON F.FACULTY_ID = C.FACULTY_ID
ORDER BY C.CREDITS DESC;


-- ========== PART F (Aggregate) ==========

-- 17
SELECT C.COURSE_NAME, COUNT(E.STUDENT_ID) AS TOTAL_STUDENTS
FROM COURSE C
INNER JOIN ENROLLMENT E
ON C.COURSE_ID = E.COURSE_ID
GROUP BY C.COURSE_NAME;

-- 18
SELECT F.NAME, COUNT(C.COURSE_ID) AS TOTAL_COURSES
FROM FACULTY F
INNER JOIN COURSE C
ON F.FACULTY_ID = C.FACULTY_ID
GROUP BY F.NAME;

-- 19
SELECT D.DEPARTMENT_ID, COUNT(S.STUDENT_ID) AS TOTAL_STUDENTS
FROM DEPARTMENT D
INNER JOIN STUDENT S
ON D.DEPARTMENT_ID = S.DEPARTMENT_ID
GROUP BY D.DEPARTMENT_ID;

-- 20
SELECT C.COURSE_NAME, MAX(E.GRADE) AS MAX_GRADE
FROM COURSE C
INNER JOIN ENROLLMENT E
ON C.COURSE_ID = E.COURSE_ID
GROUP BY C.COURSE_NAME;

-- ==========================================
-- END OF LAB 5

