SELECT COUNT(*) AS TOTAL_STUDENTS
FROM Student;

SELECT COUNT(*) AS TOTAL_FACULTY
FROM Faculty;

SELECT COUNT(*) AS TOTAL_COURSES
FROM Course;

SELECT MAX(CREDITS) AS MAX_CREDITS
FROM Course;

SELECT MIN(CREDITS) AS MIN_CREDITS
FROM Course;

SELECT DEPARTMENTID, COUNT(*) AS NUMBER_OF_STUDENTS
FROM Student
GROUP BY DEPARTMENTID;

SELECT DEPARTMENTID, COUNT(*) AS NUMBER_OF_FACULTY
FROM Faculty
GROUP BY DEPARTMENTID;

SELECT DEPARTMENTID, COUNT(*) AS NUMBER_OF_COURSES
FROM Course
GROUP BY DEPARTMENTID;

SELECT SEMESTER, COUNT(*) AS TOTAL_ENROLLMENTS
FROM Enrollment
GROUP BY SEMESTER;

SELECT GRADE, COUNT(*) AS NUMBER_OF_STUDENTS
FROM Enrollment
GROUP BY GRADE;

SELECT DEPARTMENTID, COUNT(*) AS TOTAL_STUDENTS
FROM Student
GROUP BY DEPARTMENTID
HAVING COUNT(*) > 3;

SELECT SEMESTER, COUNT(*) AS TOTAL_ENROLLMENTS
FROM Enrollment
GROUP BY SEMESTER
HAVING COUNT(*) > 2;

SELECT GRADE, COUNT(*) AS TOTAL_STUDENTS
FROM Enrollment
GROUP BY GRADE
HAVING COUNT(*) > 1;

SELECT DEPARTMENTID, COUNT(*) AS TOTAL_COURSES
FROM Course
GROUP BY DEPARTMENTID
HAVING COUNT(*) > 1;

SELECT COURSEID, COUNT(STUDENTID) AS ENROLLED_STUDENTS
FROM Enrollment
GROUP BY COURSEID;

SELECT Course.COURSENAME, COUNT(Enrollment.STUDENTID) AS ENROLLED_STUDENTS
FROM Course
JOIN Enrollment
ON Course.COURSEID = Enrollment.COURSEID
GROUP BY Course.COURSENAME;

SELECT DEPARTMENTID, COUNT(STUDENTID) AS TOTAL_STUDENTS
FROM Student
GROUP BY DEPARTMENTID;

SELECT Faculty.NAME, COUNT(Course.COURSEID) AS COURSES_TAUGHT
FROM Faculty
JOIN Course
ON Faculty.FACULTYID = Course.FACULTYID
GROUP BY Faculty.NAME;

SELECT Course.COURSENAME, MAX(Enrollment.GRADE) AS MAX_GRADE
FROM Course
JOIN Enrollment
ON Course.COURSEID = Enrollment.COURSEID
GROUP BY Course.COURSENAME;

SELECT DEPARTMENTID, COUNT(*) AS TOTAL_COURSES
FROM Course
GROUP BY DEPARTMENTID;

SELECT SEMESTER, COUNT(STUDENTID) AS TOTAL_STUDENTS
FROM Enrollment
GROUP BY SEMESTER;

SELECT COURSEID, COUNT(STUDENTID) AS TOTAL_STUDENTS
FROM Enrollment
GROUP BY COURSEID
HAVING COUNT(STUDENTID) > 2;